### ISSUE TITLE
How use ConfigFactory.load extra config file at Android ?

### ISSUE THREAD

**Issue by CMingTseng** [mathias21/KtorEasy#8]
Dear Sir

very thx your demo

i also ref other demo

this one use extra config file : "application.$environment.conf"

if i run ktor server at android with the same config

do you know how load ?

because "ConfigFactory.load" base on ClassLoader

THX

https://github.com/samgarasx/ktor-webapi/blob/0a9b0c56879a00919d62fdd8b9933e2e45e6309d/src/main/kotlin/ktorwebapi/Server.kt#L15

**Comment by mathias21** [comment]
Hi @CMingTseng 

I'm not aware how is Android doing to load Ktor server config internally. I've seen many people asking something similar in Kotlinlang Slack channel. Maybe you can try to get some answers here:
https://app.slack.com/client/T09229ZC6/C0A974TJ9

This is the link to Ktor channel in Kotlinlang Slack workspace.
